<?php

return [

    'companies' => [
        [
            'id' => 'rama',
            'name' => 'RAMA Technologies',
            'role' => 'Senior Software Engineer — Full Stack',
            'period' => 'May 2025 – Present',
            'years' => ['from' => 2025, 'to' => null],
            'blurb' => 'Digital loan origination and credit-assessment platforms — secure REST APIs integrating AI-driven risk engines, with audit logging and compliance-aligned backend logic.',
            'skills' => ['nodejs', 'laravel', 'rest-api', 'security', 'ai-integration'],
            'accent' => 'gold',
            'current' => true,
        ],
        [
            'id' => 'herogram',
            'name' => 'Herogram',
            'role' => 'Senior Software Engineer — Full Stack (AI Products)',
            'period' => 'Jan 2024 – Apr 2025',
            'years' => ['from' => 2024, 'to' => 2025],
            'blurb' => 'Led development on large-scale AI-based web products, designing scalable RESTful APIs that integrate frontend and AI components.',
            'skills' => ['nodejs', 'react', 'ai-integration', 'mentorship'],
            'accent' => 'teal',
            'current' => false,
        ],
        [
            'id' => 'brainwave',
            'name' => 'Brainwave Technologies',
            'role' => 'Senior Full Stack Developer',
            'period' => 'Dec 2022 – Oct 2023',
            'years' => ['from' => 2022, 'to' => 2023],
            'blurb' => 'Built and maintained large-scale applications end to end, creating efficient REST APIs for smooth cross-platform mobile and web communication.',
            'skills' => ['rest-api', 'mobile-integration', 'php'],
            'accent' => 'teal',
            'current' => false,
        ],
        [
            'id' => 'tekrevol',
            'name' => 'Tekrevol',
            'role' => 'Senior Software Engineer — Backend',
            'period' => 'Mar 2021 – Dec 2022',
            'years' => ['from' => 2021, 'to' => 2022],
            'blurb' => 'Architected core server-side components across multiple Agile/Scrum projects, keeping API contracts consistent between backend, frontend and mobile teams.',
            'skills' => ['backend-architecture', 'agile', 'rest-api'],
            'accent' => 'teal',
            'current' => false,
        ],
        [
            'id' => 'abtach',
            'name' => 'Abtach',
            'role' => 'Full Stack Web Developer',
            'period' => 'Jan 2018 – Dec 2020',
            'years' => ['from' => 2018, 'to' => 2020],
            'blurb' => 'Developed custom modules and integrated APIs into large-scale systems, with a focus on performance, security audits and data protection.',
            'skills' => ['php', 'security', 'performance'],
            'accent' => 'teal',
            'current' => false,
        ],
    ],

    'skills' => [
        ['id' => 'nodejs', 'label' => 'Node.js', 'group' => 'backend', 'fact' => 'Node.js — APIs powering AI-driven credit-risk engines at RAMA.'],
        ['id' => 'laravel', 'label' => 'Laravel', 'group' => 'backend', 'fact' => 'Laravel — backend architecture across fintech and travel platforms.'],
        ['id' => 'php', 'label' => 'PHP', 'group' => 'backend', 'fact' => 'PHP — 7+ years building and securing large-scale systems.'],
        ['id' => 'nestjs', 'label' => 'NestJS', 'group' => 'backend', 'fact' => 'NestJS — structured, scalable API design.'],
        ['id' => 'python', 'label' => 'Python', 'group' => 'backend', 'fact' => 'Python — automation and AI-adjacent tooling.'],
        ['id' => 'rest-api', 'label' => 'REST API Design', 'group' => 'backend', 'fact' => 'REST API design — consistent contracts across mobile, web and AI systems.'],
        ['id' => 'react', 'label' => 'React.js', 'group' => 'frontend', 'fact' => 'React.js — interfaces for AI-based web products.'],
        ['id' => 'nextjs', 'label' => 'Next.js', 'group' => 'frontend', 'fact' => 'Next.js — modern, fast-loading frontends.'],
        ['id' => 'vuejs', 'label' => 'Vue.js', 'group' => 'frontend', 'fact' => 'Vue.js — reactive UI for internal tools and dashboards.'],
        ['id' => 'mysql', 'label' => 'MySQL', 'group' => 'db', 'fact' => 'MySQL — relational data at production scale.'],
        ['id' => 'postgresql', 'label' => 'PostgreSQL', 'group' => 'db', 'fact' => 'PostgreSQL — reliable storage for financial data.'],
        ['id' => 'mongodb', 'label' => 'MongoDB', 'group' => 'db', 'fact' => 'MongoDB — flexible schema for fast-moving products.'],
        ['id' => 'aws', 'label' => 'AWS', 'group' => 'devops', 'fact' => 'AWS — cloud infrastructure for production systems.'],
        ['id' => 'cicd', 'label' => 'CI/CD', 'group' => 'devops', 'fact' => 'CI/CD pipelines — shipping safely and often.'],
        ['id' => 'security', 'label' => 'Security', 'group' => 'craft', 'fact' => 'Security audits — access control and compliance-aligned backend logic.'],
        ['id' => 'performance', 'label' => 'Performance', 'group' => 'craft', 'fact' => 'Performance tuning — systems that hold up under real load.'],
        ['id' => 'ai-integration', 'label' => 'AI Integration', 'group' => 'craft', 'fact' => 'AI integration — connecting products to real AI-driven engines.'],
        ['id' => 'mobile-integration', 'label' => 'Mobile Integration', 'group' => 'craft', 'fact' => 'Mobile integration — cross-platform API communication.'],
        ['id' => 'backend-architecture', 'label' => 'Backend Architecture', 'group' => 'craft', 'fact' => 'Backend architecture — clear separation of concerns at scale.'],
        ['id' => 'agile', 'label' => 'Agile/Scrum', 'group' => 'leadership', 'fact' => 'Agile/Scrum — delivery across cross-functional teams.'],
        ['id' => 'mentorship', 'label' => 'Mentorship', 'group' => 'leadership', 'fact' => 'Mentorship — training and elevating junior developers.'],
    ],

];
